### ISSUE TITLE
I'm probably being stupid but.... Access Keys + CORS

### ISSUE THREAD

**Issue by PaulMcGuinness** [mattsalt/national-rail-darwin#14]
The ReadMe's don't explain what the Darwin_Token is. 

Is it the Access Key or Secret Key in the national rail "my feeds" or do I need to register for a different API access?

CORS... it's driving me mental. How can I disable cors - I've event tried hacking headings into the Bluebird index.js - no matter what call I make (and I'm doing this through Vue.js in case that's the issue?) I get:-

Access to fetch at 'https://lite.realtime.nationalrail.co.uk/OpenLDBWS/ldb11.asmx' from origin 'http://127.0.0.1:8844' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I suspect it's something to do with the :8844 port number on the local host?

**Comment by PaulMcGuinness** [comment]
Ignore the key thing... Found the site: 
http://realtime.nationalrail.co.uk/OpenLDBWSRegistration/Registration

Still battling with CORS... :sigh:, but have worked out that Vue / port # is the issue

**Comment by mattsalt** [comment]
Hi Paul. Glad to hear you got it sorted out. It's a good point though, the README could certainly be a bit clearer on this front. I'll get something added to this to guide people to the registration page.

Regarding the CORS issue I'm afraid I can't be of much help. I have this deployed as an AWS lambda acting as a proxy for a couple of apps rather than using a browser. Good luck though!

**Comment by PaulMcGuinness** [comment]
@mattsalt CORS is totally a PITA.... I wrote a 5-liner sample in straight node.js and it works fine.

One thing to add to the Readme as well.... even after you've registered, despite what the email says, your key won't work for about an hour
