### ISSUE TITLE
Darwin API still supported?

### ISSUE THREAD

**Issue by jackdewhurst** [mattsalt/national-rail-darwin#8]
Hi, 

I've registered with the Darwin LDBWS service and received my token but all calls through `national-rail-darwin` fail with the following error:

```
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><soap:Code><soap:Value>soap:Receiver</soap:Value></soap:Code><soap:Reason><soap:Text xml:lang="en">Unexpected server error</soap:Text></soap:Reason><soap:Detail /></soap:Fault></soap:Body></soap:Envelope>'
```

The key part being `Unexpected server error`. 

I'm using the CMD tool with the following command `darwin db LGX -t {Darwin Token Here}`.

Any ideas?
Thanks!

**Comment by mattsalt** [comment]
Hi Jack, thanks for using this tool. Is LGX a valid National Rail CRS code? Can you try with WAT for London Waterloo.

Cheers!

**Comment by jackdewhurst** [comment]
Hi Matt, thanks for making it. Was not looking forward to interacting with the SOAP API myself!

You're right WAT works, LGX must not be a valid code, I should have tried another.

LGX is currently included in your Readme `getDepartureBoard` example. Might be worth changing it to WAT or similar?

Cheers

**Comment by mattsalt** [comment]
Apologies for the late reply, I was on holiday. That's a really good point. I shall update the readme! Thanks for highlighting this.
